spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CarRentalDB
    username: your-db-username
    password: your-db-password

auth0:
  domain: your-auth0-domain
  audience: your-auth0-audience

cloudinary:
  cloud-name: your-cloud-name
  api-key: your-cloudinary-api-key
  api-secret: your-cloudinary-api-secret
