server:
  port: 8088
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: tourism-service
          uri: lb://tourism-service
          predicates:
            - Path=/tourism/**
        - id: events-service
          uri: lb://events-service
          predicates:
            - Path=/events/**
        - id: ai-chat
          uri: lb://ai-chat-service
          predicates:
            - Path=/chat/**
        - id: car-rental-service
          uri: lb://car-rental-service
          predicates:
            - Path=/rental/**
        - id: information-service
          uri: lb://information-service
          predicates:
            - Path=/information/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka