spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AuthDB
    username: your-db-username
    password: your-db-password

auth0:
  domain: your-auth0-domain
  audience: your-auth0-audience
