server:
  port: 0

spring:
  application:
    name: ai-chat-service
  config:
    import: optional:file:src/main/resources/application-secret.yml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
